[features]
seeds = false
skip-lint = false
[programs.localnet]
vrf_client = "DQiap4465pYr8MqFS3VzSG8NkVLNJeVP6rQNQ1eSwwD4"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nero/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
